//
//  TradeOrder.swift
//  MoonAlarm
//
//  Created by Kenneth Vaczi on 1/21/18.
//  Copyright © 2018 Vaczoway Solutions. All rights reserved.
//

import Foundation

class TradeOrder {
    
    // Fixed Properties //
    
    let symbolPair: String
    let side: BinanceAPI.OrderSide
    let type: BinanceAPI.OrderType
    let isTestOrder: Bool
    let orderPrice: Price?                          // Not necessary for market orders
    let quantityOrdered: Double
    let timeInForce: BinanceAPI.TimeInForce         // assume processed immediately
    var startTime: Milliseconds = ExchangeClock.instance.currentTime
    
    // Mutating Properties //

    var uid: String? = nil                          // Generated by binance, set after processing
    var status: BinanceAPI.OrderStatus = .new       // Updated after processing
    var quantityFilled: Double = 0                  // Updated after processing
    var fills: TradeOrderFills = []                 // Keep track of individual fills
    
    /// Average fill price for this trade order, excluding fees
    var avgfillPrice: Price? {
        
        // Server says we've filled orders
        guard self.quantityFilled > 0 else { return nil }
    
        // Limit order may not have fills, price is at limit price
        if  self.type == .limit,
            let price = self.orderPrice {
            return price
        }
        
        // Market order will have fills
        if self.type == .market {
            guard self.fills.count > 0 else { return nil }
            return fills.avgFillPrice
        }
        
        return nil  // Not sure
    }
    
    // Initializers //
    
    init(pair: String, side: BinanceAPI.OrderSide, type: BinanceAPI.OrderType = .market,
         price: Price? = nil, timeInForce: BinanceAPI.TimeInForce = .ioc,
         quantity: Double, isTest: Bool = true) {
        self.symbolPair = pair
        self.side = side
        self.type = type
        self.orderPrice = price
        self.timeInForce = timeInForce
        self.quantityOrdered = quantity
        self.isTestOrder = isTest
    }
    
    // Methods //
    
    func execute(callback: @escaping (_ isSuccess: Bool) -> Void) {
        guard self.status == .new else { callback(false); return }
        BinanceAPI.instance.postNewOrder(for: self) {
            (isSuccess, processedOrder) in
            callback(isSuccess)
        }
    }

}
