//
//  TradeOrder.swift
//  MoonAlarm
//
//  Created by Kenneth Vaczi on 1/21/18.
//  Copyright © 2018 Vaczoway Solutions. All rights reserved.
//

import Foundation

class TradeOrder {
    
    // Fixed Settings //
    
    let symbolPair: String
    let side: BinanceAPI.OrderSide
    let type: BinanceAPI.OrderType
    let isTestOrder: Bool
    let orderPrice: Price?                          // Not necessary for market orders
    let quantityOrdered: Double
    let timeInForce: BinanceAPI.TimeInForce         // assume processed immediately
    
    // Mutating Settings //
    
    
    var uid: String? = nil                          // Generated by binance, set after processing
    var status: BinanceAPI.OrderStatus = .new       // Updated after processing
    var avgfillPrice: Price? = nil                  // Updated after filled
    var quantityFilled: Double = 0                  // Updated after filled
    
    init(pair: String, side: BinanceAPI.OrderSide, type: BinanceAPI.OrderType = .market,
         price: Price?, timeInForce: BinanceAPI.TimeInForce = .ioc,
         quantity: Double, isTest: Bool = true) {
        self.symbolPair = pair
        self.side = side
        self.type = type
        self.orderPrice = price
        self.timeInForce = timeInForce
        self.quantityOrdered = quantity
        self.isTestOrder = isTest
    }
    
    func execute(callback: @escaping (_ isSuccess: Bool) -> Void) {
        guard self.status == .new else { callback(false); return }
        BinanceAPI.instance.postNewOrder(for: self) {
            (isSuccess, processedOrder) in
            callback(isSuccess)
        }
    }

}
